### PR TITLE
Cleanup of translations

### PR DESCRIPTION
**Pull request by Eric-01**
The changes made as a part of this pull request are as follows:
* removed lines that have been removed from the source English translation but remained in others
* made sure that all lines in all translation files are in the same order as in the source English one — this resulted in a few rearrangements in some translation files
* unified indentations to always use 2 whitespace characters per indentation level
* unified line endings to always use LF (this issue can be permanently resolved in the future by adding a `.gitattributes` file, but this is out of scope of this PR)
* added missing newlines at the ends of a few translation files.

### CODE REVIEW

**Review by Lhoerion — APPROVED** [review]

**Review by C0kkie — APPROVED** [review]
Looks good

**Comment by Eric-01** [comment]
Thank you for accepting.

**Comment by Eric-01** [comment]
Thank you.

**Comment by C0kkie** [comment]
Thanks for your contribution ^^

**Pull request merged**
