### PR TITLE
new locales for lv.json

### PR DESCRIPTION
**Pull request by LightSrc**

### CODE REVIEW

**Comment by C0kkie** [comment]
Hi

thanks for contribution
could you add the few missing ones too?

**Comment by LightSrc** [comment]
Which ones are missing? When I edit I campare en.json with lv.json and has 0 missing keys.

**Comment by C0kkie** [comment]
> Which ones are missing? When I edit I campare en.json with lv.json and has 0 missing keys.

Looks like you added it on the wrong places
They need to be at the same places where the en ones are

**Comment by C0kkie** [comment]
Thank you :)

**Pull request merged**
